export const ACTION_TYPES = {
    CHANGE_THEME: "CHANGE_THEME",
    USER_LOGIN: "LOGIN",
    USER_LOGOUT: "LOGOUT",
    SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
    CLOSE_NOTIFICATION: "CLOSE_NOTIFICATION",
};
